// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/profiles/avatar_6.png
var ResourceAvatar4PngData []byte
var ResourceAvatar4Png = &fyne.StaticResource{
	StaticName:    "assets/profiles/avatar_6.png",
	StaticContent: ResourceAvatar4PngData,
}
