// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/profiles/avatar_2.png
var ResourceAvatar2PngData []byte
var ResourceAvatar2Png = &fyne.StaticResource{
	StaticName:    "assets/profiles/avatar_2.png",
	StaticContent: ResourceAvatar2PngData,
}
