// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/profiles/avatar_1.png
var ResourceAvatar1PngData []byte
var ResourceAvatar1Png = &fyne.StaticResource{
	StaticName:    "assets/profiles/avatar_1.png",
	StaticContent: ResourceAvatar1PngData,
}
