// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/logo.png
var ResourceLogoPngData []byte
var ResourceLogoPng = &fyne.StaticResource{
	StaticName:    "assets/logo.png",
	StaticContent: ResourceLogoPngData,
}
