// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/profiles/role_admin.png
var ResourceRoleAdminPngData []byte
var ResourceRoleAdminPng = &fyne.StaticResource{
	StaticName:    "assets/profiles/role_admin.png",
	StaticContent: ResourceRoleAdminPngData,
}
