// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/profiles/avatar_3.png
var ResourceAvatar3PngData []byte
var ResourceAvatar3Png = &fyne.StaticResource{
	StaticName:    "assets/profiles/avatar_3.png",
	StaticContent: ResourceAvatar3PngData,
}
