// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package ui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/profiles/role_operator.png
var ResourceRoleOperatorPngData []byte
var ResourceRoleOperatorPng = &fyne.StaticResource{
	StaticName:    "assets/profiles/role_operator.png",
	StaticContent: ResourceRoleOperatorPngData,
}
